---
title: "Population Genetics 2025"
author: "Andrius J. Dagilis"
---

# Welome to PopGen!

This is the website for Population Genetics (EEB 5348) at UConn. Here you will find notes on each of the lectures, links to papers and other materials as they become needed.

# About the course

The focus of this course is to introduce graduate students to population genetic thinking. I firmly believe the greatest benefit of population genetics is not knowledge of any particular approach or methodology (there are too many for any course to cover adequately), but a firm grasp of how population genetics can be used to 1) test and hone your intuition of evolutionary processes, 2) understand how (and why) different population genetics approaches work and 3) develop heuristics to examine any system of interest. Throughout the course we will examine classic population genetics results, read recent literature that either uses those results or throws them completely into question and work on developing a set of scripts and skills in a language of your choice (although I will recommend either `Julia` or `R`) to investigate the population genetics of different data-sets.

# Schedule/General Logistics

Each week, we will start with a lecture on Tuesday, followed by a paper discussion and lab on Thursday. The goal of this class structure is to be able to introduce general concepts/remind you of things you should remember from your Genetics/Evolution courses, introduce classic PopGen results, followed by a more in-depth dive in the state of the art uses of those results and some practical advice of coding how they work. Here's a general week-by-week overlay of the topics. Lecture notes will be added as links as we go along

| Week | Topic(s) | Reading | Lecture Notes |
|------------------|------------------|------------------|------------------|
| Aug 26-28 | Intro, Wright-Fisher | [Leu et al](notes/papers/Leu2020.pdf) | [Lecture 1](notes/Lecture1.qmd) |
| Sep 2-4 | Genetic diversity measurements | [Buffalo](notes/papers/Buffalo2021.pdf) | [Lecture 2](notes/Lecture2.qmd) |
| Sep 9-11 | Divergence at a site, mutation, molecular models of evolution | [Peede et al](notes/papers/Peede2025.pdf) | [Lecture 3](notes/Lecture3.qmd) |
| Sep 16-18 | Sexual reproduction, Recombination, LD | [Hahn and Mishra](notes/papers/HahnMishra2025.pdf) |[Lecture 4](notes/Lecture4.qmd) |
| Sep 23-25 | Population structure, migration, the coalescent | [Cousins et al](notes/papers/Cousins2025.pdf)  | [Lecture 5](notes/Lecture5.qmd) |
| Sep 30-Oct 2 | Selection at a single locus, types of selection | [Ketchum et al](https://www.biorxiv.org/content/10.1101/2025.07.06.663360v1.abstract) | [Lecture 6](notes/Lecture6.qmd) |
| Oct 7-9 | Project Meetings, no regular class | NA |  |
| Oct 14-16 | Quantitative trait evolution | [Chen and Pannell](https://www.cell.com/current-biology/fulltext/S0960-9822(25)00451-8) | [Lecture 7](notes/Lecture7.qmd) |
| Oct 21-23 | Confounded selection, demography, mutation | [Joquera et al.](https://academic.oup.com/mbe/article/42/3/msaf053/8088191) | [Lecture 8](notes/Lecture8.qmd) |
| Oct 28-30 | Accounting for selection/demography in trait evolution | [Lecture 9](notes/Lecture9.qmd) | [Wellenreuther et al.](https://www.cell.com/trends/ecology-evolution/fulltext/S0169-5347(25)00225-3) |
| Nov 4-6 | Ancestral Recombination Graphs (and where to find them) | [Lecture 10](notes/Lecture10.qmd) | [Terhorst](https://www.nature.com/articles/s41588-025-02323-x) |
| Nov 11-13 | Students' choice - Conservation Genetics |  |  |
| Nov 18-20 | Students' choice - Data Visualization in Genomics |  |  |
| Nov 25-27 | THANKSGIVING BREAK |  |  |
| Dec 2-4 | Project meetings, final projects due Dec 4 | NA |  |