---
title: "Syllabus"
---

# EEB 5348: Population Genetics

This graduate-level course is designed to introduce students to the fundamentals of population genetics, including modeling and data analysis. The course is composed of lectures, paper discussions and computer labs. Throughout the course, the students are expected to learn: 1) core derivations of classical population genetics results, 2) both intuitive and technical understanding of many population genetic statistics meant to measure genetic diversity, the impact of different evolutionary forces (migration, selection, mutation, non-random mating), as well as 3) develop a set of scripts in a programming language of their choice to calculate such statistics on existing data-sets. While the course does not have a formal requirement in a course focusing on sequence data generation and processing, such knowledge will be helpful for students who want to work on their own data. Evaluation is primarily composed of participation, both in weekly quizzes/homeworks, discussion sections and group projects. An individual project will be worth 25% of the grade, and will allow students to analyze the population genetic history of a population of their choice. 

## Grading

Grading is based on four main components:
1) Weekly quizzes/homeworks: 24%
    You will receive a weekly quiz or assignment during Tuesday lectures. These will be due before end of the day on Friday.

## Course Schedule

## Where to look for help

## 

## Academic conduct

## Use of AI

This section is left seperate from academic conduct on purpose. Use of AI approaches in this class is permissable, but needs to be clearly acknowledged and done with clear purpose. Asking an AI assistant (ChatGPT, Copilot, Gemini, Claude, etc.) for help debugging code is a legitimate use of AI for the purpose of the class, but may lead you astray if the code generated does not do what you expect. As such, any AI generated code should be flagged as such (so I know where potential errors stem from). AI assistant use in generating technical reports, answering homework problems, performing mathematical derivations, summarizing readings in lieu of reading the assigned material, or any other purpose I've forgotten to mention here but you know better than to do is not permissable. The entire ethos of this course is to let you develop a keen intuition when it comes to population genetics - the only approach to do this is to actually read papers, analyze and think through the models and data. You will often be wrong, and the grading takes that into account by focusing on assignment submission and your rationale over correct answers. Use of AI in these cases therefore circumvents precisely what I want you to learn, and will be treated as academic misconduct. 