---
title: Lab 2
theme: cosmo
bibliography: references.bib
engine: julia
execute:
  freeze: auto  # re-render only when source changes
---

# Lab 3: Genetic divergence estimates

Today we'll keep working with genetic data in `R`. The goal is to get those who did not import data last time to import genomic data, think about how it is structured, and build a few more functions that are useful to take a glance at your own data. As we go along, I will also point out packages/software that could have done what we are doing for us more easily, but which you decide to use is up to you. My goal is to make sure you understand how these methods work, how genetic data is structured, and what you'll need for different analyses.

# Part 1: Calculating $F_{ST}$

In this first part, we'll continue to work on calculating heterozygosity, and calculate $F_{ST}$ for a VCF split between two populations.

## Importing VCFs:

Today we'll work with a different vcf than last time. In the data folder you should be able to find `muc19.vcf.gz`. This is a subsample of the 1000 genomes project data centered around the MUC19 gene. This dataset includes