---
title: Lab 7
theme: cosmo
bibliography: references.bib
execute:
  freeze: auto  # re-render only when source changes
  eval: false
  echo: true
engine: julia
---

# Setting up for your final project.

The first goal of today's lab is to make sure you start with a good structure for your final project. We've already talked about good practice here, but I'll re-state it and _really_ encourage you to try it out. Every week from now, we'll focus at least part of the lab time to work on your final project. Don't treat this as the _only_ time to work on your projects, rather, as a good time to check in and make sure we can help you with any issues you are running into. Today, we'll make sure you have your data in a project folder, that that project folder has all the basics you'll need, and that you start making git commits (and even git pushes) to back up your progress.

## Project directory

Since most of you are using `R`, start by opening `R` and creating a new project. Choose a new directory for this project, and then either "New Project" or "Quarto Project" if you are using `Quarto`. Create _with_ a git repository - I will be strongly encouraging (read: I will look more favorably on your final project) consistent git commits on your project. This should leave you with a folder structure that looks like:

```{bash}
.
├── .Rproj.user
│   ├── D313530A
│   │   ├── bibliography-index
│   │   ├── ctx
│   │   ├── explorer-cache
│   │   ├── pcs
│   │   │   ├── files-pane.pper
│   │   │   ├── source-pane.pper
│   │   │   ├── windowlayoutstate.pper
│   │   │   └── workbench-pane.pper
│   │   ├── presentation
│   │   ├── profiles-cache
│   │   ├── sources
│   │   │   └── session-f8c769d6
│   │   │       └── lock_file
│   │   ├── tutorial
│   │   └── viewer-cache
│   └── shared
│       └── notebooks
│           └── patch-chunk-names
├── .git
│   ├── HEAD
│   ├── config
│   ├── description
│   ├── hooks
│   │   ├── applypatch-msg.sample
│   │   ├── commit-msg.sample
│   │   ├── fsmonitor-watchman.sample
│   │   ├── post-update.sample
│   │   ├── pre-applypatch.sample
│   │   ├── pre-commit.sample
│   │   ├── pre-merge-commit.sample
│   │   ├── pre-push.sample
│   │   ├── pre-rebase.sample
│   │   ├── pre-receive.sample
│   │   ├── prepare-commit-msg.sample
│   │   ├── push-to-checkout.sample
│   │   ├── sendemail-validate.sample
│   │   └── update.sample
│   ├── info
│   │   └── exclude
│   ├── objects
│   │   ├── info
│   │   └── pack
│   └── refs
│       ├── heads
│       └── tags
├── .gitignore
└── MyFinalProject.Rproj
```

### If you decide to use something else last minute

Some of you will be running analyses that are not easy to execute from inside `R`, so you may not want to work with `R`. That's fine! I will still recommend you create a simple project structure that includes: 1) Base directory, scripts folder, and a markdown file to write up your process. 2) Directory for data where raw/processed data lives. 

If you decide you want to use `Julia` - check out [DrWatson](https://juliadynamics.github.io/DrWatson.jl/dev/) - it will not only set up the project directory neatly, but will also add some really useful functionality within `Julia`, like returning absolute paths from within any scripts running in the project directories, etc.

## Moving your data in and making your first commit.

Add your data (vcf/metadatad) to a folder called `data`. One important note here as you start using git: you will first want to open a .gitignore file in the base directory, and add `data/*` to it. This is to make sure that you don't add your data to the git commits: git is very bad at managing big files, and some of you will have big files. 

Move your <last_name>.R source file from the PopGen folder to this new project directory. You now have a quick set of analyses on your vcf that _should_ function well enough for a first pass analysis. 

Then, open up a new Markdown (or Quarto) file in the base directory, and call it `Project.md`(or `Project.qmd`). Write a brief description of what the goals of your project are (that we discussed in meetings last week). 

Finally, make your first git commit on the project folder. Before you do, call me over so we can make sure it's looking correctly configured.

## What now?

If you have your project directory set up, start with the first, basic analysis that most of you will need to run: look for population structure in your data. You know how to do this - make Plink files out of your `vcf`, then run `PCAngsd`. Instead of _just_ running these things, make sure you start writing things up in your markdown file. For instance, you could start with something like this:

``````{markdown}
## Analysis 1: Population Structure

We'll start with a cursory population structure analysis. For this, I'll be using Plink version ??? and PCAngsd version ???. I ran the following commands:

```{bash}
plink --vcf data/myvcf.vcf.gz --make-bed --out
```
And then we run PCAngsd as ...

``````

# GWAS in R

Once you are done setting up your directory, your task for the day is to get GWAS running in `R` using its example data. The guide is found [here](https://cran.r-project.org/web/packages/statgenGWAS/vignettes/GWAS.html). Follow along until you get to the Manhattan Plots, but use the "plant.height" trait rather than "grain.yield", and send me your result.

